### ISSUE TITLE
Plans: FAQ layout issues in IE11

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#11534]
Today, I noticed an issue where the FAQ section has an awkward layout on IE11. This happens for both WP.com and Jetpack plans. Macnchrome seems Ok.

![screen shot 2017-02-22 at 11 31 45 am](https://cloud.githubusercontent.com/assets/1126811/23224172/e0a1cbf6-f8f2-11e6-96f8-a253349cde3e.png)

Same layout issue for Jetpack sites:

![screen shot 2017-02-22 at 11 31 00 am](https://cloud.githubusercontent.com/assets/1126811/23224187/eb6cfa60-f8f2-11e6-822a-c0b5006eac8c.png)

**Comment by sirreal** [comment]
IE is not correctly calculating the width of the columns which is causing overflow.

```css
 		width: calc( ( 100% - 48px ) / 3 );
 		margin-left: 24px;
 		 
 		&:nth-child( 3n+1 ) {
 			margin-left: 0;
 		}
```

The calculated logic looks correct and, indeed, other browsers get it right. IE11 misses it 😭 

At the arbitrary container width 752, it displays calculated columns as 234.67px wide, resulting in the following:

234.67px * 3 columns + 48px internal margins = **752.01px**

This overflows the container and wraps the third column.
