### ISSUE TITLE
Media Section: Fix sticky nav styling for smaller viewports

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#12076]
Currently as we scroll down the action bar doesn't fully cover the div behind.

![nav](https://cloud.githubusercontent.com/assets/1270189/23869658/034161d8-07e1-11e7-96bf-07db17ccd408.gif)

### To reproduce:
- Navigate to http://calypso.localhost:3000/media
- Resize your window to something small
- Select a site
- Scroll down

**Comment by retrofox** [comment]
The `perspective` CSS rule breaks the `fixed` position of the sticky panel.

https://github.com/Automattic/wp-calypso/blob/master/client/components/main/style.scss#L26

```css
@include breakpoint( "<660px" ) {
  backface-visibility: hidden;
  perspective: 1000;
}
```
