### ISSUE TITLE
Store: Incorrect styling of Dashboard checkmarks in Safari

### ISSUE THREAD

**Issue by dechov** [Automattic/wp-calypso#18825]
From the Store Dashboard in Safari (10.1.1):

<img width="418" alt="Black checkmark circles on Dashboard" src="https://user-images.githubusercontent.com/1867547/31503487-c94319e0-af3d-11e7-9453-9169fba114de.png">

Looks like the [following rule](https://github.com/Automattic/wp-calypso/pull/17317/files#diff-147e46b60c9879428873057a18248220R100) is taking precedence over the `$alert-green` due to its greater specificity:
```scss
	.dashboard__setup-task-status:not(.dashboard__setup-task-status .gridicon){
		background-color: black;
		color: black;
	}
```

My thought is: if the intent is to make it `black` except if it contains a `.gridicon`, that's not possible to encode in CSS as such I don't think, but as written it basically means "status div that isn't also a gridicon that's the child of another status div". We can revise this rule and/or tweak the specificity so that the green shows up.
