### ISSUE TITLE
Gutenlypso: wrong publish button annimation

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29267]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post
2. Write some test content and click on Publish.
3. Upon confirming the Publish, notice the weird animation on the button.

![publish button](https://user-images.githubusercontent.com/1182160/49687752-e2032580-fb07-11e8-9d53-0b4e4d8ee247.gif)

The button size shouldn't be animated at all. Also one more important note for debugging is that this can't be reproduced with latest master in dev. Seem to only be affecting wpcalypso and horizon.

**Comment by sirreal** [comment]
This is due to a collision between mangled CSS animation names. Namely, the Gutenberg `.components-button.is-busy` animation is colliding with the animate appear animation, which leads to undesired results. The sources involved:

### Gutenberg styles

```sass
.components-button {
	// snip …
	&.is-busy {
		animation: components-button__busy-animation 2500ms infinite linear;
		background-size: 100px 100%;
		background-image: repeating-linear-gradient(-45deg, $light-gray-500, $white 11px, $white 10px, $light-gray-500 20px);
		opacity: 1;
	}
	// snip …
}
@keyframes components-button__busy-animation {
	0% {
		background-position: 200px 0;
	}
}

```
https://github.com/WordPress/gutenberg/blob/13459da2de90fba6279668b8ab6771020e8f4a2b/packages/components/src/button/style.scss#L178-L183
https://github.com/WordPress/gutenberg/blob/13459da2de90fba6279668b8ab6771020e8f4a2b/packages/components/src/button/style.scss#L228-L232

### Enter Calypso styles

The above styles work well enough in isolation, however the following styles are also loaded:

https://github.com/Automattic/wp-calypso/blob/8c5b3696db9fe1bb7346d6cc681455567e5a7903/client/components/animate/style.scss#L6-L14

### So?

The animation names in the sources don't collide, however some build step run for production builds is mangling the names. That's why the issue isn't present in development. The styles are effectively the following:

```css
.components-button.is-busy {
	animation: a 2500ms infinite linear;
	// snip …
}
// 👍 All good
@keyframes a {
	0% {
		background-position: 200px 0;
	}
}
// 🤦‍♂️ Oh wait, that's ignored ☝️ 
// 💥 Animation is overwritten 👇 
 @keyframes a { 
 	0%, 
 	20% { 
 		transform: scale( 0, 0 ); 
 	} 
 	100% { 
 		transform: scale( 1, 1 ); 
 	}
 } 
```

> If multiple keyframe sets exist for a given name, the last one encountered by the parser is used. @keyframes rules don't cascade, so animations never derive keyframes from more than one rule set.
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes#Resolving_duplicates)

### Check it out!

These are current builds of stylesheets loaded in the editor. Search for `@keyframes a` in both of them and you'll see the issue:

```css
@keyframes a{0%{background-position:200px 0}}
```
https://wpcalypso.wordpress.com/calypso/gutenberg-editor.5553ac50908a32ff8a5c.css

```css
@keyframes a{0%,20%{transform:scale(0)}to{transform:scale(1)}}
```
https://wpcalypso.wordpress.com/calypso/build.a4bf0136982a999f910a.css

### What's the solution?

I haven't tracked down where exactly this occurs, but the most simple solution may be to disable this type of name mangling from CSS minification.
