### ISSUE TITLE
Review/remove usages of moz-document url-prefix() hack

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#32388]
There are several CSS rules like this:
```css
@-moz-document url-prefix() {
  .firefox .specific {
    override: 1px;
  }
}
```
That are supposed to be understood and interpreted only by Firefox.

According to this article the hack has stopped working some time ago:
https://stackoverflow.com/questions/3123063/what-does-moz-document-url-prefix-do

Found when reviewing #32386.
