### ISSUE TITLE
Gutenboarding: upgrade plans grid visuals and copy

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40822]
This is how plans grid currently looks like in Gutenboarding before launching the site, or if the user chooses a paid domain:

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/87168/78583105-07f52300-783f-11ea-9c30-675a1fdf23f0.png">

### Copy when purchasing domain

@johnHackworth [suggests](https://github.com/Automattic/wp-calypso/pull/40813#issuecomment-609876812) this copy:

> Pick one of our paid plans to get [domain] for your site!
> You can change to any other plans later, and upgrade as you grow.
>
> Not sure yet? start with the _free plan_ and select a paid domain later!

In Figma we have this:

> Choose a plan
> Pick a plan that's right for you. Switch plans as you needs change. There's no risk, you can cancel for a full refund within 30 days.

### Copy when launching

> Choose a plan
> Pick a plan that's right for you. Switch plans as you needs change. There's no risk, you can cancel for a full refund within 30 days.

## Styles

Eventually, we'll want it to look like this:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/87168/78583402-76d27c00-783f-11ea-82e3-81c59b4cf38f.png">

For this calypso grid we don't want to do very heavy modifications, so let's stick to very basics. I'm not sure if these modifications I'm suggesting are "too much" CSS overrides and would just render the whole thing too unstable. @johnHackworth what's the timeline when we'd work on a custom grid? We might also just decide to replace the header with our custom header and leave the grid CSS without overrides. I don't think using a completely white background with the current grid works without further CSS overrides.

Just pseudo-code to give direction:

```css 
body {
   background: #fff;
}

.plan-features__header {
  border-color: transparent;
}

tr:last-child .plan-features__table-item,
tr:first-child .plan-features__table-item {
  border-radius: 0;
}

.plan-features__header,
.plan-features__table th,
.plan-features__table td {
  background: rgba(248, 248, 248, 0.7);
}

.plan-price__integer {
  font-weight: 500;
}

.plan-price__integer {
  font-weight: 500;
}

.plan-features__header-title {
  font-weight: 500;
}

.wordpress-logo { 
  display: none;
}
```

For the heading section:

- Use Recoletta font for the 1st heading.
- Left-align text
- Remove W logo
- Right align "free plan"
- Generally aim to match header in Figma. Can we replace the header completely, instead of doing CSS overrides?

We would end up with something like this:

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/87168/78585438-8d2e0700-7842-11ea-9bb4-db5147d67cf9.png">

@olaolusoga @dubielzyk @johnHackworth thoughts?
