### ISSUE TITLE
InlineHelp: Ensure hover/focus styles for selected items in support search results

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#43616]
## Description

The support search results do not provide any indicator when the selected result item is hovered/focused. 

Whilst arrow keys are correctly used to navigate between items it should presumably still be possible to hover/focus the items and therefore we should have a visual indicator of this.

It looks like there was some attempt to do this in the CSS but it was misapplied so it never works. We should consider tweaking it as per the below... 

## Original Issue

I don't think it does anything. There is no background on these `a` elements. 

I _think_ the intention was to provide an indicator to the user when the hovered or focused a "selected" result item in order that it was obvious where the current focus was.

Perhaps what we want is:

```scss
&.is-selected {
    background: var( --color-primary );
    cursor: pointer;
    color: var( --color-text-inverted );

    &:hover,
    &:focus {
        background: none;
    }

    a {
        color: var( --color-text-inverted );
    }
}
```

Notice how I've moved the focus styles onto the `<li>` so that we can see when the selected item is focused. Try this out by using arrows to select an item and then using `TAB` to move the focus around.

_Originally posted by @getdave in https://github.com/Automattic/wp-calypso/pull/43429_
