### ISSUE TITLE
FSE: Add upgrade indicator to premium blocks

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#44048]
#### Steps to reproduce

1. Starting at URL:
2.
3.
4.

**Comment by obenland** [comment]
@sfougnier @jancavan Is there a chance I could defer to you for the creation of that star SVG?

**Comment by jancavan** [comment]
@obenland I think we already have a star icon, or at least it's showing the [G2 icon Figma](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=4388%3A0). Is it not in the repo?

**Comment by obenland** [comment]
It is, thanks. I updated the issue description with a reference to a pre-existing implementation.

**Comment by cpapazoglou** [comment]
Previous exploration https://ajaxp2.wordpress.com/2020/02/12/premium-block-identification-icon-inventory

**Comment by cpapazoglou** [comment]
Previous exploration paYJgx-rs-P2

**Comment by frontdevde** [comment]
Digging into this a bit, I found there was a prior attempt made in a similar direction: 

https://github.com/Automattic/jetpack/pull/13490/files#diff-bb769916a770ad52c514ba7ab6609e48R54

Wondering if we could go a similar route using `<Dashicon icon="star-filled" />` instead and then adjusting the position of the star icon via CSS as needed.

**Comment by jancavan** [comment]
Just an FYI - the Premium visual indicators should disappear as per @sfougnier.

See pbAPfg-EE-p2-#comment-1374

cc @obenland @Automattic/ajax

**Comment by jeryj** [comment]
Looked into this a little with @mreishus. One idea was to use `::after` to add in an SVG to the icons. This adds a circle to every icon:

```scss
.block-editor-block-icon::after {
    display: block;
    content: '';
    width: 24px;
    height: 24px;
    position: absolute;
    background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='2' cy='2' r='2'/%3E%3C/svg%3E");
}
```

<img width="700" alt="Screen Shot 2020-07-14 at 4 54 30 PM" src="https://user-images.githubusercontent.com/967608/87480650-60348180-c5f3-11ea-9ca4-15ae11ac6bcc.png">


**Since we only want it on Paid blocks, we'd have to curate that list of blocks:**

```scss
// specify which blocks we want this to show up for
.editor-block-list-item-jetpack-recurring-payments,
.editor-block-list-item-jetpack-simple-payments {
    .block-editor-block-icon::after {
        display: block;
        content: '';
        width: 24px;
        height: 24px;
        position: absolute;
        transform: translateX(100%);
        background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle fill='red' cx='2' cy='2' r='2'/%3E%3C/svg%3E");
    }
}
```

However, this only works for the block selector. It doesn't appear everywhere the block icon is used (Preview, Inline Inserter). I didn't see named classes for places like the `/` inline inserter, so we wouldn't be able to target those icons.

<img width="697" alt="Screen Shot 2020-07-14 at 4 53 36 PM" src="https://user-images.githubusercontent.com/967608/87480899-e3ee6e00-c5f3-11ea-88ba-e5c4f5e97568.png">

**The last option we explored was adding the `Circle` directly into the SVG of the icon.**

```jsx
export const icon = (
	<SVG xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
		<Rect x="0" fill="none" width="24" height="24" />
		<G>
			<Path d="M20 4H4c-1.105 0-2 .895-2 2v12c0 1.105.895 2 2 2h16c1.105 0 2-.895 2-2V6c0-1.105-.895-2-2-2zm0 2v2H4V6h16zM4 18v-6h16v6H4zm2-4h7v2H6v-2zm9 0h3v2h-3v-2z" />
		</G>
		<Circle fill="red" cx="24" cy="3" r="4"/>
	</SVG>
);
```

<img width="699" alt="Screen Shot 2020-07-14 at 4 58 01 PM" src="https://user-images.githubusercontent.com/967608/87481036-29ab3680-c5f4-11ea-9b06-11c2ae466bb1.png">

This gets us the red circle on every icon since it's embedded within it. The issue then is, **how do we manage appending the extra SVG to the end of the icon?** Some quick ideas:

- Having multiple copies of paid icons. 
- Somehow injecting our SVG dynamically to the end of the Icon component (we didn't see a way to do this, but it would be amazing)
- In paYJgx-rs-p2 we had explored adding a separate SVG (so the icon would be made up of two SVGs instead of one), but that was not a recommended path.
- ???

Any other ideas? If we can append the SVG inside of the existing block icons so it's one `<svg>` element, then we should be good to go on displaying the star icon.
