### ISSUE TITLE
Toggle component lost pointer

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49995]
Toggles lost pointer-cursor appearance on Calypso:

https://user-images.githubusercontent.com/87168/107658229-97a10480-6c8e-11eb-96cd-816bd835256b.mov

Works on Gutenberg:

https://user-images.githubusercontent.com/87168/107658255-9d96e580-6c8e-11eb-903b-28f44fb39a4d.mov

I assume we don't have the same CSS reset as core anymore?

```css
input[type="checkbox"], input[type="radio"] {
  cursor: pointer;
}
```

cc @Automattic/team-calypso
