### ISSUE TITLE
Enable Anti-aliasing in Dotcom

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52192]
Enable font smoothing CSS across all of .com admin interfaces, including —

- [x] Calypso
- [x] Calypso Jetpack green 
- [x] Regular wp-admin, iframed block editor, and iframed Customizer
- [x] [All separate entrypoints](https://github.com/Automattic/wp-calypso/tree/4d8155849c9a164f1b964adcd4528f149399259d/client/landing)

Not in themes, nor at frontends of the sites.

Context p9Jlb4-2ur-p2

I did a small spike into this — feel free to close and start over fresh: https://github.com/Automattic/wp-calypso/pull/52014

Here's the CSS:

```css
body {
	text-rendering: optimizeLegibility;
	-moz-osx-font-smoothing: grayscale;
	-webkit-font-smoothing: antialiased;
}
```

There are [some additional aspects](https://github.com/WordPress/WordPress/search?q=subpixel-antialiased) of wp-admin that need special handling, such as the masterbar. Same [in the editor](https://github.com/WordPress/gutenberg/search?q=subpixel-antialiased).
