### ISSUE TITLE
GuidedTours: WebPreview spinner obscured by step on mobile

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#5696]
Raised in https://github.com/Automattic/wp-calypso/pull/5693#issuecomment-222746055

<img src="https://cloud.githubusercontent.com/assets/4389/15682448/9f52ee88-2755-11e6-8760-5aa4135d64bd.png" />

The spinner inside the preview at mobile sizes is a bit too high, and in the tour gets hidden behind the dialog (screenshot without dialog).

**Comment by lsinger** [comment]
Unclear whether moving the spinner for this one case makes sense. The CSS has a special case for the vertical positioning of the spinner on mobile, which moves it further up: 

```SCSS
.web-preview .spinner {
	margin-left: -10px;
	position: absolute;
		top: 45%;
		left: 50%;

	@include breakpoint( "<660px" ) {
		top: 20%;
	}
}
```

The step doesn't obscure the spinner at 50%: 

<img width="168" alt="screen shot 2016-06-03 at 3 22 32 pm" src="https://cloud.githubusercontent.com/assets/23619/15780396/b7106c3c-29a1-11e6-8a01-b54284953de7.png">

@shaunandrews @folletto any opinions on whether we should move the spinner down? We don't want to have a special case in which we move the spinner down only if a tour is running. That would be sad.
