### ISSUE TITLE
Seller Experience - Payment block upgrade message is obscured by toolbar

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61419]
When using the block editor to edit a Payments block (as in the site editor after onboarding through the Sell flow), a user with a free plan has the upgrade prompt obscured when clicking into the block. We need to update this design to make sure that call to action is not obscured.

![image](https://user-images.githubusercontent.com/13437011/155404927-e46a6c0e-a856-4e03-a465-683cbc5ee453.png)

(Further demonstration available at p1645645871002379-slack-C0Q664T29)

**Comment by Copons** [comment]
This seems to be caused by this code, but I'm not sure where it comes from:
```css
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > * + *,
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > * + * {
  margin-top: var( --wp--style--block-gap );
}
```

Furthermore, the upgrade nudge button is incorrectly using some theme styles, such as the link underline (see [Blockbase](https://github.com/Automattic/themes/blob/de7a2473bb920fe3a8f5c33432bd2e7ad158e586/blockbase/sass/elements/_links.scss#L13-L22)):
<img width="127" alt="Screenshot 2022-02-24 at 14 33 07" src="https://user-images.githubusercontent.com/2070010/155545807-01fcc998-a698-425e-abfe-58dff3adbae4.png">
We should make sure the upgrade button overrides the underline in Jetpack:
- https://github.com/Automattic/jetpack/blob/862a3f107ad02346a4571b78f8aea3b9e066f744/projects/plugins/jetpack/extensions/shared/components/upgrade-nudge/style.scss
- https://github.com/Automattic/jetpack/blob/862a3f107ad02346a4571b78f8aea3b9e066f744/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/editor.scss
