### ISSUE TITLE
Editor / Site -- Code Block(s)

### ISSUE THREAD

**Issue by rfaile313** [Automattic/wp-calypso#64888]
#### Steps to reproduce

Look at:

Editor link: https://wordpress.com/post/sretips.wordpress.com/22
Post link: sretips.wordpress.com

#### What I expected

In the editor:

1. For code blocks to display vertically in line with the page and not weirdly far left. Example:

<img width="1047" alt="Screen Shot 2022-06-23 at 3 46 59 AM" src="https://user-images.githubusercontent.com/13829168/175257659-8c1276d2-9e37-4e77-976e-1ce52fb79f00.png">

If you go to the page in the editor (and feel free to go there and make changes to test) try adding a code block.

2. For me to be able to move out of the code block into the next block either by pressing enter or clicking the mouse below it or something. If you're in a code block, you have no way to move the cursor out that I have found, except by clicking into a previous non-code block and doing something there.

On the page:

1. For formatting to not be randomly jacked up, it looks like maybe the whitespace distance is not being respected?

<img width="918" alt="Screen Shot 2022-06-23 at 3 49 53 AM" src="https://user-images.githubusercontent.com/13829168/175258286-6dc540ff-7536-4577-9ffa-961abd9fab08.png">

example of same exact paste here in markdown code snippet (no sensitive info, same as post) -- notice how much better this looks / this is what I would expect from a code block in general:

```
mysql> SHOW SLAVE STATUS \G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 44.44.44.44
                  Master_User: username
                  Master_Port: 1111
                Connect_Retry: 60
              Master_Log_File: binlog.042607
          Read_Master_Log_Pos: 38558083
               Relay_Log_File: relaylog.042872
                Relay_Log_Pos: 38558290
        Relay_Master_Log_File: binlog.042607
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 38558083
              Relay_Log_Space: 38558653
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 26697682123
                  Master_UUID: 8b47fe70-cf77-22eb-8107-b8599f2164fa
             Master_Info_File: /var/lib/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
1 row in set (0.00 sec)
```

2. for some sort of indication that this is meant to be code / a code block and not looking like a paragraph 

#### What happened instead

Above

#### Browser / OS version

FireFox 101.0.1
MacOS Monterey 12.4

#### Screenshot / Video

Above

#### Context / Source

I was just making a post 

#dogfooding - I use our product(s)
