### ISSUE TITLE
Publication theme: 'Fixed' background option doesn't work for 'full-width' cover blocks

### ISSUE THREAD

**Issue by kavyagokul** [Automattic/wp-calypso#75372]
### Quick summary

When using a cover block, if you set it to fullwidth, and select fixed background, the parallax effect doesn't work.

### Steps to reproduce

1. Start with a site on the Publication theme
2. Create or edit a page
3. Add a cover block, select an image.
4. Set the block to full width
5. Select the 'Fixed background' option on the right side.
6. Publish or save, and preview the page

### What you expected to happen

The cover block scrolls with a fixed background

### What actually happened

The cover block's background scrolls with the content

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by dpasque** [comment]
Reproduced and confirmed this is specific to just the Publication Theme!

It looks like this has to do with how this theme applies styles to full alignment items:

```css
.no-sidebar .alignfull {
    width: 100vw;
    max-width: 100vw;
    margin-left: 0;
    margin-right: 0;
    position: relative;
    left: 50%;
    transform: translateX(-50%);
}
```

Specifically, the `transform` seems to be what is disrupting the parallax effect.

I haven't worked out what the smoothest option would be, but if folks really wanted it for this theme in the meantime, you should be able to massage this with some custom CSS, but it might be a bit involved 😅 

Transferring to themes repo, and lowering the priority given the more narrow impact, and that it's limited to CSS.  👍
