### ISSUE TITLE
Feature Request: Add ability to change color and thickness of Timeline Block

### ISSUE THREAD

**Issue by eoinsav** [Automattic/wp-calypso#81859]
### What

It would be great if there were some Block Settings to change the color and thickness of the Timeline Block. Right now there are no available settings apart from the ability to alternate items.

<img width="200" alt="Screenshot 2023-09-18 at 2 08 05 PM" src="https://github.com/Automattic/wp-calypso/assets/35590156/0773197c-eb7e-4859-b319-336c13d113fa">

### Why

Right now it requires CSS to change the style of the line.

```css
/*Change color*/
.wp-block-jetpack-timeline li.wp-block-jetpack-timeline-item .timeline-item:after, 
.wp-block-jetpack-timeline li.wp-block-jetpack-timeline-item .timeline-item__bubble {
	background: #989898;
}
```

```css
/*Change thickness*/
.wp-block-jetpack-timeline li.wp-block-jetpack-timeline-item .timeline-item:after {
	width: 2px;
	left: -34px;
}

.wp-block-jetpack-timeline li.wp-block-jetpack-timeline-item .timeline-item__bubble {
	height: 2px;
	left: -34px;
}
```

----

There is a related issue, but that is looking for more complex enhancements: https://github.com/Automattic/wp-calypso/issues/45484
