### ISSUE TITLE
"Download Woocomemrce app" banner breaks the wp-admin dashboard on mobile screens

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wp-calypso#96861]
### Quick summary

The Woo header / mobile app installation banner is half-visible when the left menu in wp-admin is open.

Original issue: https://github.com/woocommerce/woocommerce/issues/52832

Since this issue is only happening on WPCOM, we transferred the issue from WooCommerce repository to Calypso

### Steps to reproduce

1. Access an AT site with WooCommerce installed
2. Go to Woocommerce > Home
3. Check the header

Note: Use Android mobile device or dev tools > Simulate a Android mobile device.

### What you expected to happen

The banner should be fully visible or hidden when left menu is open.

### What actually happened

The banner is only half-visible when the left menu is open.

Check the video

https://github.com/user-attachments/assets/d184e8b4-8b29-48ae-a269-7122b05c6785

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Temporary Fix Using CSS

```css
/* For mobile view */

/* Increase z-index of WPCOM admin menu */
.auto-fold .wp-responsive-open #adminmenuback {
    z-index: 9999; /* Adjust to be higher than WooCommerce header */
}

/* OR Reduce the z-index of the WooCommerce header */
.woocommerce-layout__header {
    z-index: 100; /* Lower than WPCOM admin menu */
}
```

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes
- deleted as we don't need them
